version: "3.9"

services:
  n8n:
    build: .
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=superbezpiecznehaslo
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - WEBHOOK_URL=http://n8n-master:5678
      - TZ=Europe/Warsaw
      - N8N_CORS_ALLOW_ORIGIN=*
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./data:/app/data:rw
      - ./assets:/app/assets
      - ./scripts:/app/scripts
      - ./renderer:/app/renderer
    depends_on:
      - quiz-api
      - quiz-renderer

  
  n8n-runner:
    build: .
    container_name: n8n-runner
    restart: always
    ports:
      - "5679:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=runner
      - N8N_BASIC_AUTH_PASSWORD=superhaslo
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - WEBHOOK_URL=http://n8n-runner:5678
      - TZ=Europe/Warsaw
      - N8N_CORS_ALLOW_ORIGIN=*
    volumes:
      - ./n8n_data:/home/node/.n8n       # wspólna baza workflowów (do importu/edycji)
      - ./data:/app/data:rw
      - ./assets:/app/assets
      - ./scripts:/app/scripts
      - ./renderer:/app/renderer

  quiz-api:
    build:
      context: ./scripts
    container_name: quiz-api
    ports:
      - "8000:8000"
    working_dir: /app
    volumes:
      - ./scripts:/app
      - ./data:/app/data:rw
    restart: unless-stopped

  quiz-renderer:
      build:
        context: ./renderer
      container_name: quiz-renderer
      working_dir: /app
      volumes:
        - ./renderer:/app
        - ./data:/app/data:rw
      ports:
          - "8001:8000"
      restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: quiztok-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # izoluje node_modules wewnątrz kontenera
    working_dir: /app
    environment:
      - NODE_ENV=development
      - REACT_APP_ULTRAFAST_WEBHOOK=http://n8n-runner:5678/webhook-test/d6745df8-6e8c-4186-8ef1-73213526f7ad
      - REACT_APP_STANDARD_WEBHOOK=http://n8n-master:5678/webhook-test/d6745df8-6e8c-4186-8ef1-73213526f7ad
    restart: unless-stopped

