version: "3.9"

services:
  n8n:
    build: .
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=superbezpiecznehaslo
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - WEBHOOK_URL=http://localhost:5678
      - TZ=Europe/Warsaw
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./data/audio:/app/data/audio
      - ./data/json:/app/data/json
      - ./data/images:/app/data/images
      - ./data/images/output_buttons:/app/data/images/output_buttons
      - ./data/video:/app/data/video
      - ./data/output:/app/output
      - ./assets:/app/assets
      - ./scripts:/app/scripts
      - ./renderer:/app/renderer
    depends_on:
      - quiz-api
      - quiz-renderer

  quiz-api:
    build:
      context: ./scripts
    container_name: quiz-api
    ports:
      - "8000:8000"
    working_dir: /app
    volumes:
      - ./scripts:/app
      - ./data:/app/data
    restart: unless-stopped

  quiz-renderer:
      build:
        context: ./renderer
      container_name: quiz-renderer
      working_dir: /app
      volumes:
        - ./renderer:/app
        - ./data:/app/data
      ports:
          - "8001:8000"
      restart: unless-stopped

